In [4]:

import os
os.environ['DATA_ROOT'] = '/work/sarandi/data'
#from smplfit.pt.converter import BodyModelConverter


#converter = BodyModelConverter('smpl', 'neutral', 'smplx', 'neutral')

In [5]:
from smplfit.np.fitting import Fitter
from smplfit.np.smpl import SMPL 
smpl_model = SMPL(model_name='smpl', gender='neutral')
smplx_model = SMPL(model_name='smplx', gender='neutral')
fitter  = Fitter(smpl_model, num_betas=10)

ImportError: cannot import name 'Fitter' from 'smplfit.np.fitting' (/home/sarandi/rwth-home2/pose/pycharm/smplfit/smplfit/np/fitting.py)

In [4]:
import trimesh
import numpy as np
meshes = np.stack([np.array(trimesh.load_mesh(p).vertices) for p in paths])
meshes = meshes.astype(np.float32)[:2]

In [5]:
fit_res = fitter.fit(meshes, n_iter=1, beta_regularizer=0,
                     requested_keys=['pose_rotvecs', 'shape_betas'])

In [13]:
converter_smplx2smpl = BodyModelConverter('smplx', 'neutral', 'smpl', 'neutral')

NameError: name 'BodyModelConverter' is not defined

In [7]:
pose_, betas_, trans_ = converter.convert(fit_res['pose_rotvecs'], fit_res['shape_betas'], fit_res['trans'])

In [8]:
true_verts = smpl_model(fit_res['pose_rotvecs'], fit_res['shape_betas'], fit_res['trans'])['vertices']

smplx_verts = smplx_model(pose_, betas_, trans_)['vertices']
smpllike_verts = converter_smplx2smpl.convert_vertices(smplx_verts)

error = (smpllike_verts - true_verts).norm(dim=-1).mean()

In [6]:
fit_res

{'shape_betas': array([[ 0.13640113,  0.6937035 , -0.48801613, -0.13726428,  0.86108166,
          0.6606184 ,  0.9717764 ,  0.41420475,  0.31663826,  0.3799744 ],
        [ 0.18556167,  0.9670995 ,  0.17373087,  0.16577812,  0.53767323,
          0.22402374,  0.32619   ,  0.01546325, -0.4082278 ,  0.24927801]],
       dtype=float32),
 'kid_factor': None,
 'trans': array([[ 0.00195017,  0.00073077,  0.00352168],
        [-0.00264719,  0.00327193,  0.00182936]], dtype=float32),
 'relative_orientations': array([[[[ 9.36896503e-01,  1.51230723e-01,  3.15204769e-01],
          [-2.19384521e-01, -4.47667480e-01,  8.66870344e-01],
          [ 2.72204369e-01, -8.81318986e-01, -3.86240423e-01]],
 
         [[ 9.37620003e-01, -3.28548279e-01,  1.13686680e-01],
          [ 2.91215579e-01,  9.20827055e-01,  2.59366817e-01],
          [-1.89900306e-01, -2.10080167e-01,  9.59064168e-01]],
 
         [[ 9.73921076e-01,  1.35480374e-01,  1.81996365e-01],
          [-2.08405757e-01,  2.17083261e-01,  

In [11]:
from smplfit.pt.fitting import Fitter
from smplfit.pt.smpl import SMPL 
smpl_model = SMPL(model_name='smpl', gender='neutral')
smplx_model = SMPL(model_name='smplx', gender='neutral')
fitter  = Fitter(smpl_model, num_betas=10)

In [13]:
import torch
fit_res = fitter.fit(torch.tensor(meshes[:1]), n_iter=1, beta_regularizer=0,
                     requested_keys=['pose_rotvecs', 'shape_betas'])

In [14]:
fit_res

{'shape_betas': tensor([[ 0.1363,  0.6938, -0.4880, -0.1373,  0.8613,  0.6607,  0.9718,  0.4146,
           0.3160,  0.3801]]),
 'kid_factor': None,
 'trans': tensor([[0.0020, 0.0007, 0.0035]]),
 'relative_orientations': tensor([[[[ 9.3690e-01,  1.5122e-01,  3.1518e-01],
           [-2.1937e-01, -4.4767e-01,  8.6687e-01],
           [ 2.7219e-01, -8.8132e-01, -3.8625e-01]],
 
          [[ 9.3762e-01, -3.2854e-01,  1.1369e-01],
           [ 2.9122e-01,  9.2084e-01,  2.5933e-01],
           [-1.8989e-01, -2.1004e-01,  9.5907e-01]],
 
          [[ 9.7396e-01,  1.3544e-01,  1.8185e-01],
           [-2.0825e-01,  2.1705e-01,  9.5369e-01],
           [ 8.9693e-02, -9.6672e-01,  2.3960e-01]],
 
          [[ 9.7651e-01, -9.4101e-02, -1.9382e-01],
           [-3.2358e-02,  8.2533e-01, -5.6373e-01],
           [ 2.1301e-01,  5.5676e-01,  8.0290e-01]],
 
          [[ 9.8890e-01,  4.1396e-02, -1.4273e-01],
           [-1.1810e-01,  8.0188e-01, -5.8570e-01],
           [ 9.0207e-02,  5.9605e-01,  7

In [1]:
from smplfit.pt.lstsq import lstsq_partial_share
import torch
# lstsq_partial_share(matrix, rhs, weights, l2_regularizer, n_shared=0)

matrix = torch.randn(2, 4, 3)
rhs = torch.randn(2, 4, 1)
weights = torch.ones_like(torch.randn(2, 4))
l2_regularizer = torch.tensor([0.1]*3)
n_shared = 2

lstsq_partial_share(matrix, rhs, weights, l2_regularizer, n_shared)



tensor([[[ 0.0189],
         [-0.4737],
         [-0.0064]],

        [[ 0.0189],
         [-0.4737],
         [-0.4949]]])

In [2]:
from smplfit.tf.lstsq import lstsq_partial_share as lstsq_partial_share_tf
import tensorflow as tf

2024-10-26 17:10:28.369511: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-26 17:10:28.369553: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-26 17:10:28.370724: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-26 17:10:28.376566: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-26 17:10:29.183411: W tensorflow/compiler/tf2

In [3]:
matrix_ = tf.constant(matrix.numpy())
rhs_ = tf.constant(rhs.numpy())
weights_ = tf.constant(weights.numpy())
l2_regularizer_ = tf.constant(l2_regularizer.numpy())

lstsq_partial_share_tf(matrix_, rhs_, weights_, l2_regularizer_, n_shared)

2024-10-26 17:10:31.081763: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-10-26 17:10:31.083529: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[ 0.01888187],
        [-0.47367266],
        [-0.00641382]],

       [[ 0.01888187],
        [-0.47367266],
        [-0.49486515]]], dtype=float32)>

In [1]:
from smplfit.np.lstsq import lstsq_partial_share as lstsq_partial_share_np
matrix_ = matrix.numpy()
rhs_ = rhs.numpy()
weights_ = weights.numpy()
l2_regularizer_ = l2_regularizer.numpy()

lstsq_partial_share_np(matrix_, rhs_, weights_, l2_regularizer_, n_shared)

NameError: name 'matrix' is not defined

In [2]:
import os
os.environ['DATA_ROOT'] = '/work/sarandi/data'
from smplfit.pt.converter import SMPLConverter
import simplepyutils as spu
from smplfit.pt.fitting import SMPLfit
from smplfit.pt.smpl import SMPL
import trimesh
import numpy as np
import torch

paths = spu.sorted_recursive_glob('/work/sarandi/data/bedlam/smplx/transfer_data/meshes/smpl/*.ply')
meshes = np.stack([np.array(trimesh.load_mesh(p).vertices) for p in paths])
meshes = meshes.astype(np.float32)[:2]

import smplfit.pt

#fn = smplfit.pt.get_fit_fn('smpl', 'neutral', device='cuda')

fit_res = smplfit.pt.fit(torch.tensor(meshes).cuda())

#with torch.device('cuda'):
#    smpl_model = SMPL(model_name='smpl', gender='neutral')
#    smplx_model = SMPL(model_name='smplx', gender='neutral')
#    fitter = torch.jit.script(SMPLfit(smpl_model, num_betas=10))
#    meshes = torch.tensor(meshes).cuda()
#    fit_res = fn(
#    fit_res = fitter.fit(
#        meshes, n_iter=1, beta_regularizer=0,
#        requested_keys=('pose_rotvecs', 'shape_betas'))


'cuda:0'

In [2]:
with torch.inference_mode(), torch.device('cuda'):
    converter_smpl2smplx = torch.jit.script(SMPLConverter('smpl', 'neutral', 'smplx', 'neutral'))
    convert_result = converter_smpl2smplx.convert(
        fit_res['pose_rotvecs'], fit_res['shape_betas'], fit_res['trans'])
    
    
    

/home/sarandi/micromamba/envs/py10/lib/python3.10/site-packages/torch/utils/_device.py:106: UserWarning: Sparse CSR tensor support is in beta state. If you miss a functionality in the sparse tensor support, please submit a feature request to https://github.com/pytorch/pytorch/issues. (Triggered internally at ../aten/src/ATen/SparseCsrTensorImpl.cpp:53.)
  return func(*args, **kwargs)


In [3]:
with torch.inference_mode(), torch.device('cuda'):
    converter_smplx2smpl = torch.jit.script(SMPLConverter('smplx', 'neutral', 'smpl', 'neutral'))

In [2]:
bm = SMPL(model_name='smpl', gender='neutral')


In [3]:
fitter = SMPLfit(bm, num_betas=10)

In [12]:
# seed:
torch.manual_seed(3)
beta = torch.randn(1, 10)
pose = torch.randn(1, 72) * 0.2
transl = torch.randn(1, 3) * 0.1
res = bm(pose, beta, transl)




In [15]:
f = 1.5
fit_res = fitter.fit_with_known_pose(pose, res['vertices']*f, res['joints']*f, scale_fit=True, beta_regularizer=0)
res2 = bm(pose, fit_res['shape_betas'])
#fit_res['scale_corr'] = 1
s = fit_res['scale_corr']
res2['vertices'] =  res2['vertices'] * s + fit_res['trans']
res2['joints'] =  res2['joints'] * s +  fit_res['trans']

error = (res2['vertices']/f - res['vertices']).norm(dim=-1).mean(dim=1)
print(error.numpy(), fit_res['scale_corr'],  s)

[4.1201085e-07] tensor([1.5000]) tensor([1.5000])


In [12]:
fit_smplx = converter_smpl2smplx.convert(fit_res['pose_rotvecs'], fit_res['shape_betas'], fit_res['trans'], kid_factor=torch.ones_like(fit_res['pose_rotvecs'][:, :1]))
fit2_smplx = converter_smpl2smplx.convert(fit_res['pose_rotvecs'], fit_res['shape_betas'], fit_res['trans'], kid_factor=torch.ones_like(fit_res['pose_rotvecs'][:, :1]), known_output_pose_rotvecs=fit_smplx['pose_rotvecs'])
print(fit2_smplx['shape_betas'] - fit_smplx['shape_betas'])

tensor([[ 5.2333e-05,  3.6061e-06, -7.9274e-06, -6.2883e-06,  9.5367e-07,
          3.7432e-05,  2.8133e-05, -6.7651e-06,  5.6922e-06,  2.1696e-05],
        [ 2.0713e-05, -2.3246e-06,  2.7120e-06,  9.7156e-06,  6.1393e-06,
          3.1590e-06, -5.4836e-06, -4.1723e-07, -5.4836e-06,  3.0994e-06]],
       device='cuda:0')


In [16]:
%matplotlib notebook

import matplotlib.pyplot as plt
from smpl.plotting import scatter3d, add_3d_subplot

fig = plt.figure(figsize=(12, 12), layout='constrained')
pose_ax = add_3d_subplot(fig, 1, 1, 1, view='front', focal_length=0.2, axis_range=2)

scatter3d(pose_ax, res['vertices']*f, s=1, alpha=1, marker='o', up_vector='y')
scatter3d(pose_ax, res2['vertices'] , s=1, alpha=1, marker='o', up_vector='y')

<IPython.core.display.Javascript object>

In [4]:
with torch.inference_mode(), torch.device('cuda'):
    convert_result = converter_smpl2smplx.convert(
        fit_res['pose_rotvecs'], fit_res['shape_betas'], fit_res['trans'])
    smplx_res = converter_smpl2smplx.body_model_out(**convert_result)
    smpllike_verts = converter_smplx2smpl.convert_vertices(smplx_res['vertices']).cpu().numpy()
    error = np.linalg.norm(smpllike_verts - meshes, axis=-1).mean()
    print(error)
    

0.0067959945


In [5]:
%%timeit

converter_smpl2smplx.convert(
    fit_res['pose_rotvecs'], fit_res['shape_betas'], fit_res['trans'])

73.2 ms ± 556 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
fit_res['pose_rotvecs'].shape

torch.Size([2, 72])

In [11]:
torch.jit.save(converter_smpl2smplx, "/tmp/converter_smpl2smplx.pt")

In [3]:
import torch
loaded = torch.jit.load("/tmp/converter_smpl2smplx.pt")

with torch.inference_mode(), torch.device('cuda'):
    pose_, betas_, trans_ = loaded.convert(
        fit_res['pose_rotvecs'], fit_res['shape_betas'], fit_res['trans'])

In [1]:
import os
os.environ['DATA_ROOT'] = '/work/sarandi/data'
DATA_ROOT = os.environ['DATA_ROOT']
# Obtain a batch of nonparametric vertex and joint locations (here we use random data)
import torch
from smplfit.pt import SMPL, SMPLfit
import numpy as np
# Obtain a batch of nonparametric vertex and joint locations (here we use random data)
batch_size = 8192*2
n_subset = 1024
vertex_subset = np.load(f'{DATA_ROOT}/body_models/smpl/vertex_subset_{n_subset}.npz')['i_verts']
vertices = torch.rand((batch_size, n_subset, 3)).cuda()
joints = torch.rand((batch_size, 24, 3)).cuda()

body_model = SMPL(model_name='smpl', gender='neutral').cuda() # create the body model to be fitted
fitter = SMPLfit(body_model, num_betas=10, vertex_subset=vertex_subset).cuda()  # create the fitter
fitter = torch.jit.script(fitter)  # optional: compile the fitter for faster execution
fit_res = fitter.fit(vertices, joints, n_iter=3, beta_regularizer=1)  # do the fitting
fit_res['pose_rotvecs'], fit_res['shape_betas'], fit_res['trans']


(tensor([[-1.9705, -0.2956,  2.3013,  ...,  1.8999, -0.9635, -1.4458],
         [-1.2176,  0.3625,  1.4918,  ...,  2.5871, -2.0596, -0.8300],
         [ 2.9678, -2.7550,  0.5845,  ..., -0.7625,  0.3182,  3.3971],
         ...,
         [ 0.1247, -2.4577,  2.8478,  ..., -2.6105, -0.2086,  2.6510],
         [ 0.3367,  0.8821,  2.4524,  ...,  0.0696,  0.3893, -0.5103],
         [ 2.7595,  2.4755, -0.2309,  ..., -0.0764,  1.6276,  0.3626]],
        device='cuda:0'),
 tensor([[-1.4552e+01,  2.0523e+00, -2.7425e-02,  ...,  5.2957e-03,
          -9.8480e-04, -7.6160e-03],
         [-1.4021e+01,  1.6100e+00, -1.1372e-01,  ..., -1.8498e-02,
          -1.2459e-01,  1.7693e-02],
         [-1.5352e+01,  2.4559e+00, -4.5257e-02,  ...,  1.8662e-02,
           1.4058e-03, -2.8129e-02],
         ...,
         [-1.5473e+01,  1.1571e+00, -1.0133e-01,  ...,  4.4811e-02,
          -1.4388e-01,  4.3444e-02],
         [-1.5066e+01,  1.5346e+00, -6.2453e-02,  ...,  3.2000e-02,
          -2.5215e-03, -1.9042e

In [41]:
%%timeit
fit_res = fitter.fit(vertices, joints, n_iter=1, beta_regularizer=1, final_adjust_rots=False) 

440 ms ± 5.42 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [42]:
batch_size

16384

In [43]:
16384/25

655.36